25th of March changes
MohacsiAdam/InterviewTask pull request #2
Opened 2021-03-25 15:02 UTC by MohacsiAdam

Moved username and password to config file
Generated Java classes for DB tables and initial annotation
Separated connection, statement and resultset generation from GetData
created .gitignore file and added unneeded files to it

2021-03-26 08:06 UTC, tamas-ruboczki-dynata requested changes
Please unversion jar files, see other comments.
Commit message should contain the short description of the work you commit.

2021-03-26 08:06 UTC, tamas-ruboczki-dynata commented on src/main/java/com/example/db_feladat/TableClasses/Cars.java
> +  private int isSent;
Are you sure this is the best type for ISsent?

2021-03-26 08:06 UTC, tamas-ruboczki-dynata commented on src/main/java/com/example/db_feladat/GetData.java
> +    public static void getData(){
Please use more meaningful names like getCars.

2021-03-26 08:06 UTC, tamas-ruboczki-dynata commented on src/main/java/com/example/db_feladat/GetData.java
> +        } finally {
Are you sure connection closing things should be in this place?

2021-03-26 08:06 UTC, tamas-ruboczki-dynata commented on src/main/java/com/example/db_feladat/GetData.java
> +                    if (resultSet.getRow() == 1) {
I would separate this long method to smaller ones. (For example one for person processing, one for vehicles.)

2021-03-26 08:06 UTC, tamas-ruboczki-dynata commented on src/main/java/com/example/db_feladat/GetData.java
> +                    current_part = current_part.replace("<brand>", brand);
An other method can be created for email creation.

2021-03-26 12:06 UTC, MohacsiAdam commented on build.gradle
> +    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
Right now I don't use servlet so I removed it.

2021-03-26 12:07 UTC, MohacsiAdam commented on settings.gradle
> +rootProject.name = "db_feladat"
Changed to db_task

2021-03-26 12:08 UTC, MohacsiAdam commented on src/main/java/com/example/db_feladat/DBConnection/GetResultSet.java
> +public class GetResultSet {
Renamed to GetQuerryResultsByName to better represent usage.

2021-03-26 12:09 UTC, MohacsiAdam commented on src/main/java/com/example/db_feladat/DBConnection/GetResultSet.java
> +    public ResultSet getResultSet(Statement statement) {
Renamed to getPersonAndCarDataFromQuerry.

2021-03-26 12:11 UTC, MohacsiAdam commented on src/main/java/com/example/db_feladat/GetData.java
> +    public static void getData(){
Went with CreateEmailResponse for the class and buildEmailResponse for the method name as these will be responsible for calling the subtasks that create the Email answer to the request.

2021-03-26 12:12 UTC, MohacsiAdam commented on src/main/java/com/example/db_feladat/TableClasses/Cars.java
> +  private int isSent;
Changed to boolean.

2021-03-26 12:31 UTC, MohacsiAdam commented on src/main/java/com/example/db_feladat/TableClasses/Cars.java
> +  @Column(name = "car_id", nullable = false)
You're right DB side wouldn't allow null value as primary key so I removed the nullable from @Id annotated columns.

2021-03-26 12:34 UTC, MohacsiAdam commented on src/main/java/com/example/db_feladat/DBConnection/GetResultSet.java
> +        System.out.println("Please enter your name:");
The input was used here, but I moved it to it's own class to clean up the resultset class.

2021-03-26 14:34 UTC, MohacsiAdam commented on src/main/java/com/example/db_feladat/GetData.java
> +                    if (resultSet.getRow() == 1) {
Separate methods created for both the person part and the car part.

2021-03-26 14:49 UTC, MohacsiAdam commented on src/main/java/com/example/db_feladat/GetData.java
> +                    current_part = current_part.replace("<brand>", brand);
Code restructured, now separate methods handle the overall letter creation and the creation of the letter parts.

2021-03-26 16:57 UTC, MohacsiAdam commented on src/main/java/com/example/db_feladat/DBConnection/GetConnection.java
> +            e.printStackTrace();
Added slfj4 loggers to catch clauses.

2021-03-26 16:58 UTC, MohacsiAdam commented on src/main/java/com/example/db_feladat/TableClasses/Cars.java
> +@Table(name = "Cars")
Functionality wasn't implemented yet just classes. Still on TODO list.

2021-03-29 07:00 UTC, tamas-ruboczki-dynata requested changes
Please unversion the external libraries, see other comments.

2021-03-29 10:34 UTC, ssi-hu-gabor-imre commented on src/main/java/com/example/db_task/DBConnection/GetConnection.java
> +public class GetConnection {
Class names should represent the contents inside, the actual behavior (the verbs) should be the method names.

I rather name this as a `provider` (`ConnectionProvider` for example), and later it could become a configuration class with spring.

2021-03-29 10:34 UTC, ssi-hu-gabor-imre commented on src/main/java/com/example/db_task/DBConnection/GetConnection.java
> +        return null;
Is logging the exception and returning `null` is the best way to handle issues here?
These infrastructure configuration issues (which can happen here for example) are probably a blocker for your application, so I would rather wrap them in a runtime one or just directly propagate them back to the caller.

2021-03-29 10:34 UTC, ssi-hu-gabor-imre commented on src/main/java/com/example/db_task/DBConnection/GetConnection.java
> +public class GetConnection {
Also, making these for example singleton could help a lot.

2021-03-29 10:34 UTC, ssi-hu-gabor-imre commented on src/main/java/com/example/db_task/CreateEmailResponse.java
> +            messageParts = message.split("(<carsLoopBegin>|<carsLoopEnd>)");
I think it might be better to create a wrapper for the templates, separating any templating logic and try to parse the template strings in a more clever way. 

- The order of the parts in the template are not fixed, you shouldn't rely on that (like `String message = messageParts[1];`), you should treat the whole template universally as one
- Any tag can occur more than once in the text (could be easily fixed by using `replaceAll`)
- I am pretty sure that we can omit the "car listing" part if we want to as well, so just don't rely on that

- It might be a really good idea to separate the SQL related code from the templating logic

2021-03-29 10:34 UTC, ssi-hu-gabor-imre commented on src/main/java/com/example/db_task/DBConnection/GetQuerryResultsByName.java
> +        NameInput nameInput = new NameInput();
This should be done definitely elsewhere, and the name should be a parameter of this method.
You should always try to separate different kind of logics in your code base.

2021-03-29 10:34 UTC, ssi-hu-gabor-imre commented on src/main/java/com/example/db_task/TableClasses/Cars.java
> +@Table(name = "Cars")
Cool, where are the repositories? :D

2021-03-29 10:34 UTC, ssi-hu-gabor-imre commented on src/main/java/com/example/db_task/CreateEmailResponse.java
> +                System.out.println("No cars found in database!");
Why not use the logger here?

2021-03-29 10:36 UTC, ssi-hu-gabor-imre commented
There are some minor tweaks which could be done to make the code better.
However there are only 2 big things which I think is important:
- Better separation of the templating logic and a more robust parsing of the templates
- You missed a very important and very fun part of the exercise: `Amit csak lehet, a rendszer a memóriából szolgáljon ki, az adatbázisból a leheto legkevesebbszer olvasson.`. I think you should consider implementing that as well :)

2021-03-29 13:57 UTC, MohacsiAdam commented on build.gradle
> +    implementation group: 'org.slf4j', name: 'slf4j-api', version: '2.0.0-alpha1'
Removed unneeded ones.

2021-03-29 13:57 UTC, MohacsiAdam commented on src/main/java/com/example/db_task/CreateEmailResponse.java
> +        GetQuerryResultsByName dbResultSet = new GetQuerryResultsByName();
Fixed.

2021-03-29 14:00 UTC, MohacsiAdam commented on src/main/java/com/example/db_task/CreateEmailResponse.java
> +                String sb = messagePersonData +
Changed variable name to fullMessage.

2021-03-29 14:02 UTC, MohacsiAdam commented on src/main/java/com/example/db_task/CreateEmailResponse.java
> +            throwable.printStackTrace();
Added logger.

2021-03-29 14:15 UTC, MohacsiAdam commented on src/main/java/com/example/db_task/DBConnection/GetQuerryResultsByName.java
> +        NameInput nameInput = new NameInput();
Nameinput calling moved to CreateEmailResponse and name passed as second parameter.

2021-03-29 14:16 UTC, MohacsiAdam commented on src/main/java/com/example/db_task/CreateEmailResponse.java
> +                System.out.println("No cars found in database!");
Changed printout to logger message.

2021-03-30 06:32 UTC, MohacsiAdam commented on src/main/java/com/example/db_task/DBConnection/GetConnection.java
> +public class GetConnection {
Changed Connection and Statement to singletons and renamed to ConnectionProvider and StatementProvider.

2021-04-01 06:45 UTC, MohacsiAdam commented on src/main/java/com/example/db_feladat/GetData.java
> +        } finally {
Now using Repository classes and the entity manager inside them to make sql queries so it's no longer there.

2021-04-01 06:47 UTC, MohacsiAdam commented on src/main/java/com/example/db_task/CreateEmailResponse.java
> +            messageParts = message.split("(<carsLoopBegin>|<carsLoopEnd>)");
SQL queries moved to repository class methods and only called here.

2021-04-01 06:47 UTC, MohacsiAdam commented on src/main/java/com/example/db_task/TableClasses/Cars.java
> +@Table(name = "Cars")
Created Repository classes.

2021-04-01 06:50 UTC, MohacsiAdam commented on src/main/java/com/example/db_task/CreateEmailResponse.java
> +            if (resultSet != null) {
Parts removed as SQL queries are now handled by the entity managers inside the repository classes.

2021-04-01 06:53 UTC, MohacsiAdam commented on src/main/java/com/example/db_task/DBConnection/GetConnection.java
> +        return null;
Remade into Singleton class and now instead of returning null it throws an exception if connection is null.

2021-04-01 06:57 UTC, MohacsiAdam commented on src/main/java/com/example/db_task/CreateEmailResponse.java
> +            messageParts = message.split("(<carsLoopBegin>|<carsLoopEnd>)");
Message parts are now found using regex, instead of manual separation.
Changed replace calls to replace all.

2021-06-04 08:02 UTC, closed without merging